<a href="https://colab.research.google.com/github/JBadawood/Kaggle/blob/main/Time_Series.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Time Series**
Apply machine learning to real-world forecasting tasks.

## **1- Linear Regression With Time Series**
Use two features unique to time series: lags and time steps.

### What is a Time Series?

" A **time series** is a sequence of measurements of the same variable(s) made over time. "

> Reference: [STAT 501 | Regression Methods](https://online.stat.psu.edu/stat501/lesson/t/t.2/t.2.1-autoregressive-models)


\
\
"

**تحليل السلاسل الزمنية**\
*طريقة لتحليل البيانات التي جُمعت خلال فترة زمنية.*

**Time Series Analysis**\
*A method of analyzing data gathered over a time interval.*

"

>المصدر: [معجـــم البيانـــات والـــذكاء االصطناعـــي](https://sdaia.gov.sa/ar/MediaCenter/KnowledgeCenter/ResearchLibrary/SDAIAPublications15.pdf) من الهيئة السعودية للبيانات والذكاء الاصطناعي بالتعاون مع مجمع الملك سلمان العالمي للغة العربية (الطبعة الثانية 2024)

In [1]:
import pandas as pd

هنا لدينا بيانات المبيعات اليومية لشهر أبريل لنسخة من كتاب بغلاف ورقي `Paperback` و بغلاف مقوى `Hardcover`

In [5]:
df = pd.read_csv('/content/drive/MyDrive/iMLND/Kaggle/Time_Series/book_sales.csv')

In [6]:
df

          Date  Paperback  Hardcover
0   2000-04-01        199        139
1   2000-04-02        172        128
2   2000-04-03        111        172
3   2000-04-04        209        139
4   2000-04-05        161        191
5   2000-04-06        119        168
6   2000-04-07        195        170
7   2000-04-08        195        145
8   2000-04-09        131        184
9   2000-04-10        183        135
10  2000-04-11        143        218
11  2000-04-12        141        198
12  2000-04-13        168        230
13  2000-04-14        201        222
14  2000-04-15        155        206
15  2000-04-16        243        240
16  2000-04-17        225        189
17  2000-04-18        167        222
18  2000-04-19        237        158
19  2000-04-20        202        178
20  2000-04-21        186        217
21  2000-04-22        176        261
22  2000-04-23        232        238
23  2000-04-24        195        240
24  2000-04-25        190        214
25  2000-04-26        182        200
26  2000-04-27        222        201
27  2000-04-28        217        283
28  2000-04-29        188        220
29  2000-04-30        247        259

لو نبغى نقرأ البيانات ونستخرجها بترتيب آخر غير الملف الأصل راح نكتب الكود التالي:
```
DataFrame_Sales = pd.read_csv('...book_sales.csv',
index_col = 'Date',
parse_dates=['Date'],
).drop('Paperback', axis=1)
```
حيث راح يتم جعل أول عمود هو الـ `Date` وراح يتم حذف عمود الـ `Paperback`

إضافة لذلك راح يكون عمود الـ `Date` عبارة عن `datetime`

راح نركز فقط على مبيعات الكتاب بالنسخة `Hardcover`

In [7]:
DataFrame_Sales = pd.read_csv('/content/drive/MyDrive/iMLND/Kaggle/Time_Series/book_sales.csv', index_col = 'Date', parse_dates=['Date']).drop('Paperback', axis=1)

In [8]:
DataFrame_Sales

            Hardcover
Date
2000-04-01        139
2000-04-02        128
2000-04-03        172
2000-04-04        139
2000-04-05        191
2000-04-06        168
2000-04-07        170
2000-04-08        145
2000-04-09        184
2000-04-10        135
2000-04-11        218
2000-04-12        198
2000-04-13        230
2000-04-14        222
2000-04-15        206
2000-04-16        240
2000-04-17        189
2000-04-18        222
2000-04-19        158
2000-04-20        178
2000-04-21        217
2000-04-22        261
2000-04-23        238
2000-04-24        240
2000-04-25        214
2000-04-26        200
2000-04-27        201
2000-04-28        283
2000-04-29        220
2000-04-30        259

In [9]:
DataFrame_Sales.head()

            Hardcover
Date
2000-04-01        139
2000-04-02        128
2000-04-03        172
2000-04-04        139
2000-04-05        191

### Linear Regression with Time Series

### Example - Tunnel Traffic

## **2- Trend**
Model long-term changes with moving averages and the time dummy.

## **3- Seasonality**
Create indicators and Fourier features to capture periodic change.

## **4- Time Series as Features**
Predict the future from the past with a lag embedding.

## **5- Hybrid Models**
Combine the strengths of two forecasters with this powerful technique.

## **6- Forecasting With Machine Learning**
Apply ML to any forecasting task with these four strategies.